/** Auto-generated by scripts/write-mobile-build-info.mjs — do not edit */
export const MOBILE_BUILD_INFO = {
  "version": "0.1.2",
  "versionName": "0.1.2-alpha",
  "versionCode": 3,
  "commit": "b2d3d17",
  "gitSha": "b2d3d17777b17813d92d3c8bede886f726b33041",
  "buildTime": "2026-08-16T20:12:45.822Z",
  "environment": "alpha",
  "branch": "cursor/mobile-verify-build-p0-d03e",
  "packageName": "ru.lot.marketplace.alpha"
} as const;
