/** Auto-generated by scripts/write-mobile-build-info.mjs — do not edit */
export const MOBILE_BUILD_INFO = {
  "version": "0.1.5",
  "versionName": "0.1.5-alpha",
  "versionCode": 6,
  "commit": "25766c7",
  "gitSha": "25766c78ec511bdcc4ec5a9016c16160b4173a94",
  "buildTime": "2026-08-17T07:26:35.394Z",
  "environment": "alpha",
  "branch": "cursor/mobile-p0-physical-crash-forensics-d03e",
  "packageName": "ru.lot.marketplace.alpha"
} as const;
