#!/usr/bin/env bash
# Cloud Agent install: idempotent repository setup.
# Prepares PostgreSQL, .env, Node dependencies, Prisma schema and demo data.
set -euo pipefail

cd "$(dirname "$0")/.."

# Run a command as root whether or not we're already root.
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
else
  SUDO="sudo"
fi

PG_VERSION=16
PG_CLUSTER=main
DB_NAME=marketplace
DB_USER=postgres
DB_PASSWORD=postgres

echo "==> Ensuring PostgreSQL is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  $SUDO apt-get update -y
  $SUDO apt-get install -y postgresql postgresql-contrib
fi

# Detect the installed major version (fall back to configured default).
if [ ! -d "/etc/postgresql/${PG_VERSION}/${PG_CLUSTER}" ]; then
  DETECTED="$(ls /etc/postgresql 2>/dev/null | sort -n | tail -1 || true)"
  if [ -n "${DETECTED}" ]; then
    PG_VERSION="${DETECTED}"
  fi
fi

echo "==> Starting PostgreSQL ${PG_VERSION}/${PG_CLUSTER}"
$SUDO pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start || true

# Wait for the server to accept connections.
for _ in $(seq 1 30); do
  if $SUDO -u postgres pg_isready -q 2>/dev/null; then
    break
  fi
  sleep 1
done

echo "==> Ensuring database role and database exist"
$SUDO -u postgres psql -v ON_ERROR_STOP=1 -c \
  "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
if ! $SUDO -u postgres psql -tAc \
  "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" | grep -q 1; then
  $SUDO -u postgres createdb "${DB_NAME}"
fi

echo "==> Ensuring .env exists"
if [ ! -f .env ]; then
  AUTH_SECRET_VALUE="$(openssl rand -base64 32)"
  cat > .env <<EOF
# Generated by .cursor/install.sh for the Cloud Agent dev environment.
NEXT_PUBLIC_APP_URL="http://localhost:3000"
AUTH_URL="http://localhost:3000"
NEXTAUTH_URL="http://localhost:3000"

DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}?schema=public"

# Dev-only Auth.js secret (throwaway, not a real credential).
AUTH_SECRET="${AUTH_SECRET_VALUE}"

STORAGE_PROVIDER="vercel-blob"
BLOB_READ_WRITE_TOKEN=""
BLOB_ACCESS="private"
NEXT_PUBLIC_BLOB_ACCESS="private"

# Optional payments (empty -> checkout shows a clear "not configured" notice).
STRIPE_SECRET_KEY=""
STRIPE_WEBHOOK_SECRET=""
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=""

# Optional CDEK delivery (empty -> deterministic mock provider).
CDEK_CLIENT_ID=""
CDEK_CLIENT_SECRET=""
CDEK_API_URL="https://api.edu.cdek.ru/v2"
CDEK_FROM_CITY_CODE=""
EOF
fi

# Make DATABASE_URL available to tooling (e.g. vitest) that does not read .env.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

echo "==> Installing Node dependencies"
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

echo "==> Applying Prisma migrations"
npx prisma migrate deploy

echo "==> Seeding demo data"
npm run db:seed

echo "==> Install complete"
