import type { SellerScreenBlueprint } from "./types";

export const SELLER_HOME_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_home",
  route: "(tabs)/seller-home",
  purpose: "Ответить: «Что сделать прямо сейчас, чтобы заработать больше?» — единый операционный центр дня.",
  primaryCTA: "Обработать срочные заказы",
  secondaryCTA: "Открыть кошелёк",
  informationHierarchy: [
    "Сегодня (задачи дня)",
    "Продажи (сводка)",
    "Требует внимания (риски)",
    "Последние заказы",
    "Лучшие товары",
    "Деньги",
    "Рост магазина",
    "AI рекомендации",
    "Продвижение",
    "История",
  ],
  conversionGoal: "Перевести продавца в действие по заказам, товарам или продвижению за ≤2 тапа.",
  popTelemetry: [
    "seller_home_opened",
    "seller_home_task_tap",
    "seller_home_order_tap",
    "seller_home_product_tap",
    "seller_home_finance_tap",
    "seller_home_ai_tap",
    "seller_home_promotion_tap",
  ],
  offlineBehaviour: "SecureStore snapshot `seller-home`; показать баннер «данные сохранены»; скрыть блоки без кэша.",
  loading: "SellerHomeSkeleton — shimmer по секциям blueprint.",
  error: "SectionErrorCard на уровне экрана + retry; секции без данных скрыты.",
  emptyState: "SellerHomeEmptyState — «Начните с первого товара» → Products (не CRUD-форма).",
  blocks: [
    {
      id: "today",
      title: "Сегодня",
      goal: "Сформировать список задач дня из заказов, остатков и продвижения.",
      showWhen: "sellerCapable && (tasks.length > 0 || firstVisit)",
      hideWhen: "offlineBlocked без snapshot",
      apiSource: "fetchSellerHome → orders.needAction, products.needAttention, promotion.active",
      onPress: "Tap task → deep link в Orders / Products / Promotion",
    },
    {
      id: "sales",
      title: "Продажи",
      goal: "Показать динамику продаж за сегодня/неделю.",
      showWhen: "analytics.summary.available",
      hideWhen: "нет метрик продаж",
      apiSource: "fetchSellerHome + fetchOrders (aggregate client-side Sprint 1)",
      onPress: "→ seller_analytics",
    },
    {
      id: "attention",
      title: "Требует внимания",
      goal: "Подсветить риски потери выручки: нулевой остаток, просроченные заказы.",
      showWhen: "needAction > 0 || needAttention > 0",
      hideWhen: "оба счётчика = 0",
      apiSource: "fetchSellerHome → orders.needAction, products.needAttention",
      onPress: "→ seller_orders или seller_products с фильтром",
    },
    {
      id: "recent_orders",
      title: "Последние заказы",
      goal: "Быстрый доступ к свежим заказам без перехода в полный список.",
      showWhen: "fetchOrders.items.length > 0",
      hideWhen: "нет заказов",
      apiSource: "fetchOrders (top 3 active)",
      onPress: "→ seller_orders/:id",
    },
    {
      id: "top_products",
      title: "Лучшие товары",
      goal: "Показать товары с наибольшим спросом для усиления продвижения.",
      showWhen: "fetchSellerProducts + views/favorites ranking",
      hideWhen: "нет товаров",
      apiSource: "fetchSellerProducts (sort by views)",
      onPress: "→ seller_product_detail",
    },
    {
      id: "money",
      title: "Деньги",
      goal: "Доступный баланс, ожидающие выплаты — доверие к финансам.",
      showWhen: "fetchSellerHome.money || fetchWallet",
      hideWhen: "wallet disabled",
      apiSource: "fetchSellerHome.money, fetchWallet",
      onPress: "→ seller_finance",
    },
    {
      id: "growth",
      title: "Рост магазина",
      goal: "Микро-KPI: активные SKU, конверсия, новые просмотры.",
      showWhen: "products.active > 0",
      hideWhen: "нет активных товаров",
      apiSource: "fetchSellerHome.products",
      onPress: "→ seller_analytics",
    },
    {
      id: "ai",
      title: "AI рекомендации",
      goal: "Одна главная рекомендация с confidence — что сделать для роста.",
      showWhen: "intelligence.topAction != null",
      hideWhen: "нет intelligence",
      apiSource: "fetchSellerHome.intelligence",
      onPress: "→ seller_ai_assistant или product detail",
    },
    {
      id: "promotion",
      title: "Продвижение",
      goal: "Активные кампании и CTA запуска.",
      showWhen: "promotion.active >= 0",
      hideWhen: "promotion API unavailable",
      apiSource: "fetchSellerHome.promotion",
      onPress: "→ seller_promotion",
    },
    {
      id: "history",
      title: "История",
      goal: "Лента последних действий: заказы, выплаты, изменения остатков.",
      showWhen: "activity feed available",
      hideWhen: "нет событий",
      apiSource: "fetchOrders + wallet events (client aggregate Sprint 1)",
      onPress: "→ contextual detail",
    },
  ],
};
