import type { SellerScreenBlueprint } from "./types";

export const SELLER_PRODUCTS_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_products",
  route: "(tabs)/seller-products",
  purpose: "Показать каталог продавца через призму выручки: что продаётся, что простаивает, что требует действия.",
  primaryCTA: "Открыть товар с низким остатком",
  secondaryCTA: "Поиск по каталогу",
  informationHierarchy: ["Header + KPI strip", "Search", "Filter chips (активные / внимание / нулевой остаток)", "Product cards"],
  conversionGoal: "Привести к действию по товару с риском потери продаж (остаток, просмотры без заказов).",
  popTelemetry: ["seller_products_opened", "seller_product_tap", "seller_products_search", "seller_products_filter"],
  offlineBehaviour: "Кэш списка товаров; поиск локально по кэшу.",
  loading: "SellerProductsSkeleton — grid shimmer.",
  error: "SectionErrorCard + retry.",
  emptyState: "SellerProductsEmptyState — «Добавьте первый товар на web-кабинете» (link, не CRUD).",
};

export const SELLER_PRODUCT_DETAIL_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_product_detail",
  route: "product/[id]?mode=seller",
  purpose: "Карточка товара глазами продавца: выручка, остаток, конверсия, что улучшить.",
  primaryCTA: "Исправить проблему (остаток / цена / фото)",
  secondaryCTA: "Запустить продвижение",
  informationHierarchy: ["Hero + status", "Revenue metrics", "Stock & conversion", "AI insight", "Buyer preview link"],
  conversionGoal: "Устранить блокер продаж по конкретному SKU.",
  popTelemetry: ["seller_pdp_opened", "seller_pdp_action", "seller_pdp_promote", "seller_pdp_preview_buyer"],
  offlineBehaviour: "Кэш product detail snapshot.",
  loading: "SellerProductDetailSkeleton.",
  error: "SectionErrorCard.",
  emptyState: "N/A — redirect to products if 404.",
};

export const SELLER_ORDERS_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_orders",
  route: "(tabs)/seller-sales",
  purpose: "Очередь заказов продавца — что обработать, что отгрузить, где риск штрафа.",
  primaryCTA: "Обработать следующий заказ",
  secondaryCTA: "Фильтр по статусу",
  informationHierarchy: ["Header + needAction count", "Active orders", "Completed orders", "SLA warnings"],
  conversionGoal: "Сократить время обработки заказа до минимума.",
  popTelemetry: ["seller_orders_opened", "seller_order_tap", "seller_order_action", "seller_orders_filter"],
  offlineBehaviour: "Кэш orders list (reuse buyer orders cache pattern).",
  loading: "SellerOrdersSkeleton.",
  error: "SectionErrorCard.",
  emptyState: "SellerOrdersEmptyState — «Заказы появятся после первой продажи».",
};

export const SELLER_FINANCE_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_finance",
  route: "(tabs)/wallet",
  purpose: "Прозрачность денег: доступно, в пути, история — доверие к выплатам.",
  primaryCTA: "Запросить выплату (web deep link)",
  secondaryCTA: "История операций",
  informationHierarchy: ["Balance hero", "Pending breakdown", "Recent transactions", "Payout schedule"],
  conversionGoal: "Удержать доверие и снизить обращения в поддержку по выплатам.",
  popTelemetry: ["seller_finance_opened", "seller_finance_payout_tap", "seller_finance_history_tap"],
  offlineBehaviour: "Кэш wallet snapshot.",
  loading: "SellerFinanceSkeleton.",
  error: "SectionErrorCard.",
  emptyState: "SellerFinanceEmptyState — «Финансы активируются после первой продажи».",
};

export const SELLER_ANALYTICS_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_analytics",
  route: "seller/analytics",
  purpose: "Понять где растёт и где теряется выручка — без BI-перегруза.",
  primaryCTA: "Исправить проседающий SKU",
  secondaryCTA: "Сравнить периоды",
  informationHierarchy: ["Period selector", "Revenue chart", "Top SKUs", "Conversion funnel", "Traffic sources"],
  conversionGoal: "Направить продавца к конкретному товару или кампании.",
  popTelemetry: ["seller_analytics_opened", "seller_analytics_period", "seller_analytics_drilldown"],
  offlineBehaviour: "Скрыть экран offline; показать last cached period.",
  loading: "SellerAnalyticsSkeleton.",
  error: "SectionErrorCard.",
  emptyState: "SellerAnalyticsEmptyState — «Недостаточно данных для аналитики».",
};

export const SELLER_PROMOTION_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_promotion",
  route: "seller/promotion",
  purpose: "Управление ростом через продвижение — не ads manager, а «что запустить сегодня».",
  primaryCTA: "Запустить кампанию (web deep link)",
  secondaryCTA: "Посмотреть активные",
  informationHierarchy: ["Active campaigns", "Suggested promotions", "ROI snapshot", "Budget hint"],
  conversionGoal: "Запустить или оптимизировать продвижение.",
  popTelemetry: ["seller_promotion_opened", "seller_promotion_start", "seller_promotion_campaign_tap"],
  offlineBehaviour: "Read-only cached campaigns.",
  loading: "SellerPromotionSkeleton.",
  error: "SectionErrorCard.",
  emptyState: "SellerPromotionEmptyState — «Продвижение увеличивает показы в каталоге».",
};

export const SELLER_AI_ASSISTANT_BLUEPRINT: SellerScreenBlueprint = {
  screenId: "seller_ai_assistant",
  route: "seller/ai",
  purpose: "Персональный бизнес-советник: одна рекомендация → одно действие.",
  primaryCTA: "Применить рекомендацию",
  secondaryCTA: "Задать вопрос",
  informationHierarchy: ["Top insight card", "Action queue", "Chat thread", "Confidence & reason"],
  conversionGoal: "Конвертировать AI insight в бизнес-действие.",
  popTelemetry: ["seller_ai_opened", "seller_ai_action", "seller_ai_feedback"],
  offlineBehaviour: "Показать last cached topAction.",
  loading: "SellerAiSkeleton.",
  error: "SectionErrorCard.",
  emptyState: "SellerAiEmptyState — «AI проанализирует магазин после первых продаж».",
};

export const SELLER_SHARED_BLUEPRINTS: SellerScreenBlueprint[] = [
  {
    screenId: "splash",
    route: "index",
    purpose: "Boot → seller mode detection.",
    primaryCTA: "—",
    secondaryCTA: "—",
    informationHierarchy: ["Brand", "Boot pipeline"],
    conversionGoal: "Безопасный вход в seller session.",
    popTelemetry: ["boot_completed"],
    offlineBehaviour: "Cached boot redirect.",
    loading: "Splash shimmer.",
    error: "StartupErrorScreen.",
    emptyState: "N/A",
  },
  {
    screenId: "login",
    route: "login",
    purpose: "Вход продавца с sellerCapable role.",
    primaryCTA: "Войти",
    secondaryCTA: "Поддержка",
    informationHierarchy: ["Credentials", "Trust copy"],
    conversionGoal: "Authenticated seller session.",
    popTelemetry: ["login_success", "login_failed"],
    offlineBehaviour: "Blocked.",
    loading: "PrimaryCTA progress.",
    error: "AuthErrorCard.",
    emptyState: "N/A",
  },
  {
    screenId: "profile",
    route: "(tabs)/profile",
    purpose: "Seller account center — mode switch, support, diagnostics.",
    primaryCTA: "Переключить режим",
    secondaryCTA: "Поддержка",
    informationHierarchy: ["Header", "Account", "Settings", "Danger zone"],
    conversionGoal: "Удержание и self-service.",
    popTelemetry: ["profile_opened", "profile_edit", "profile_logout"],
    offlineBehaviour: "Profile cache (existing).",
    loading: "ProfileSkeleton.",
    error: "SectionErrorCard.",
    emptyState: "N/A",
  },
];
