export const LOT_CREATE_COPY = {
  screenTitle: "Создать ЛОТ",
  restoreTitle: "Вы начали создавать ЛОТ",
  restoreBody: "Мы сохранили ваши данные. Продолжите с того места, где остановились.",
  restoreContinue: "Продолжить",
  restoreDelete: "Удалить",
  autosaveSaved: "Сохранено",
  autosaveSaving: "Сохраняем…",
  continueLabel: "Продолжить",
  publishLabel: "Опубликовать ЛОТ",
  publishReviewLabel: "Отправить на проверку",
  retryLabel: "Повторить",
  photosTitle: "Добавьте фото",
  photosHint: "Первое фото помогает покупателям понять, что вы продаёте",
  photosNext: "Продолжить",
  detailsTitle: "Что продаёте?",
  detailsHint: "Заполните поля — мы автоматически сохраняем ваш прогресс.",
  priceLabel: "Цена",
  descriptionTitle: "Расскажите подробнее",
  descriptionPlaceholder: "Например:\nСтул IKEA, новый, белый",
  previewTitle: "Проверьте ЛОТ",
  previewHint: "Если всё верно — отправьте на проверку или сохраните и вернётесь позже.",
  saveLotLabel: "Сохранить ЛОТ",
  pickupTitle: "Самовывоз",
  pickupHint: "Покупатель сможет забрать ЛОТ в выбранной точке.",
  pickupLoadError: "Не удалось загрузить точки самовывоза. Ваш ЛОТ сохранён — попробуйте ещё раз.",
  pickupSaveError: "Не удалось сохранить точку. Ваш ЛОТ сохранён.",
  uploadErrorTitle: "Не удалось загрузить фото",
  uploadErrorBody: "Проверьте интернет и попробуйте ещё раз",
  uploadError: "Не удалось загрузить фото. Ваш ЛОТ сохранён — попробуйте ещё раз.",
  uploadInProgress: "Загружаем фото…",
  uploadWaitPublish: "Подождите, фото ещё загружается",
  uriMissingOnRestore: "Фото нужно выбрать ещё раз",
  publishError: "Не получилось опубликовать ЛОТ",
  publishErrorBody: "Ваш ЛОТ сохранён. Можно попробовать ещё раз.",
  savedForReview:
    "ЛОТ сохранён. Отправьте его на проверку в разделе «Мои ЛОТы», когда будете готовы.",
  pendingReviewTitle: "Проверяем ЛОТ",
  pendingReviewBody:
    "Когда проверка закончится, мы сообщим результат.\n\nЕсли всё хорошо — ЛОТ появится у покупателей.\nЕсли нужно что-то изменить — покажем, что именно.\n\nСтатус всегда можно посмотреть в «Мои ЛОТы».",
  savedDraftTitle: "ЛОТ сохранён",
  savedDraftBody: "Вы сможете продолжить и опубликовать его позже.",
  continueLot: "Продолжить",
  networkError: "Ваш ЛОТ сохранён. Можно продолжить позже.",
  stockLabel: "Количество",
  productTypeLabel: "Тип ЛОТа",
  characteristicsTitle: "Характеристики",
  characteristicsHint: "Укажите несколько деталей, чтобы покупателю было проще найти ваш ЛОТ.",
  addCharacteristics: "Добавить характеристики",
  hideOptionalCharacteristics: "Скрыть дополнительные",
  characteristicsMissing: "Нужно заполнить ещё несколько данных",
  validationDetails: "Заполните обязательные поля — подсказка показана над кнопкой «Предпросмотр».",
  productTypeRequiredHint: "Выберите тип ЛОТа — без него предпросмотр недоступен.",
  successTitle: "ЛОТ опубликован",
  successBody: "Ваш ЛОТ теперь виден покупателям",
  successSavedTitle: "ЛОТ сохранён",
  viewLot: "Посмотреть ЛОТ",
  createAnother: "Создать ещё один",
  savedLocally: "ЛОТ сохранён. Вы можете продолжить позже.",
} as const;
