export const LOT_CREATE_COPY = {
  screenTitle: "Создать ЛОТ",
  restoreTitle: "Вы начали создавать ЛОТ",
  restoreBody: "Мы сохранили ваши данные. Продолжите с того места, где остановились.",
  restoreContinue: "Продолжить",
  restoreDelete: "Удалить",
  autosaveSaved: "Сохранено",
  autosaveSaving: "Сохраняем…",
  continueLabel: "Продолжить",
  publishLabel: "Опубликовать ЛОТ",
  retryLabel: "Повторить",
  photosTitle: "Добавьте фото",
  photosHint: "Первое фото помогает покупателям понять, что вы продаёте",
  photosNext: "Продолжить",
  detailsTitle: "Что продаёте?",
  detailsHint: "Заполните поля — мы автоматически сохраняем ваш прогресс.",
  priceLabel: "Цена",
  descriptionTitle: "Расскажите подробнее",
  descriptionPlaceholder: "Например:\nСтул IKEA, новый, белый",
  previewTitle: "Проверьте ЛОТ",
  previewHint: "Если всё верно — опубликуйте. Или сохраните и вернётесь позже.",
  saveLotLabel: "Сохранить ЛОТ",
  pickupTitle: "Самовывоз",
  pickupHint: "Покупатель сможет забрать ЛОТ в выбранной точке.",
  pickupLoadError: "Не удалось загрузить точки самовывоза. Ваш ЛОТ сохранён — попробуйте ещё раз.",
  pickupSaveError: "Не удалось сохранить точку. Ваш ЛОТ сохранён.",
  uploadErrorTitle: "Не удалось загрузить фото",
  uploadErrorBody: "Проверьте интернет и попробуйте ещё раз",
  uploadError: "Не удалось загрузить фото. Ваш ЛОТ сохранён — попробуйте ещё раз.",
  uploadInProgress: "Загружаем фото…",
  uploadWaitPublish: "Подождите, фото ещё загружается",
  uriMissingOnRestore: "Фото нужно выбрать ещё раз",
  publishError: "Не получилось опубликовать ЛОТ",
  publishErrorBody: "Ваш ЛОТ сохранён. Можно попробовать ещё раз.",
  savedForReview:
    "ЛОТ сохранён. Отправьте его на проверку в разделе «Мои ЛОТы», когда будете готовы.",
  networkError: "Ваш ЛОТ сохранён. Можно продолжить позже.",
  stockLabel: "Количество",
  productTypeLabel: "Тип ЛОТа",
  validationDetails: "Заполните название, цену, город и категорию — затем откройте предпросмотр.",
  successTitle: "ЛОТ опубликован",
  successBody: "Ваш ЛОТ теперь виден покупателям",
  successSavedTitle: "ЛОТ сохранён",
  viewLot: "Посмотреть ЛОТ",
  createAnother: "Создать ещё один",
  savedLocally: "ЛОТ сохранён. Вы можете продолжить позже.",
} as const;
